name: 'Snapshot & timestamp'
description: 'Produce new snapshot & timestamp versions if their content needs changing'

outputs:
  generated:
    description: "'true' if a new repository version was uploaded"
    value: ${{ steps.snapshot.outputs.generated }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      with:
        path: repository

    - uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435
      with:
        python-version: 3.11

    - run: pip install $GITHUB_ACTION_PATH/../../repo/
      shell: bash

    - id: snapshot
      run: |
        mkdir publish
        cd repository

        if playground-snapshot --push ../publish; then
          ls -l "../publish"
          echo "generated=true" >> $GITHUB_OUTPUT
        else
          echo "generated=false" >> $GITHUB_OUTPUT
        fi
      shell: bash

    - name: Upload repository artifact for GitHub Pages
      if: steps.snapshot.outputs.generated == 'true'
      uses: actions/upload-pages-artifact@253fd476ed429e83b7aae64a92a75b4ceb1a17cf
      with:
        path: publish/