name: 'Compile Playground repository'
description: 'Compile a deploy-ready TUF metadata repository'
inputs:
  path:
    description: 'Directory to create the metadata in'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      with:
        fetch-depth: 0

    - uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435
      with:
        python-version: 3.11

    - run: pip install $GITHUB_ACTION_PATH/../../repo/
      shell: bash

    - run: |
        playground-publish "$INPUT_PATH"
        ls "$INPUT_PATH"
      shell: bash
      env:
        INPUT_PATH: ${{ inputs.path }}
