name: Lint & test

on:
  push:
  pull_request:

permissions: {}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c

    - uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435
      with:
        python-version: "3.11"
        cache: 'pip'

    - name: Install system dependencies for e2e test
      run: |
        sudo apt-get install libfaketime softhsm2
        echo "PYKCS11LIB=/usr/lib/softhsm/libsofthsm2.so" >> $GITHUB_ENV

    - name: Install tox
      run: python -m pip install tox

    - name: Signer lint
      working-directory: playground
      run: tox -e lint-signer

    - name: Repository unit tests
      working-directory: playground
      run: tox -e test-repo

    - name: End-to-end tests
      working-directory: playground
      run: tox -e test-e2e
