name: repository-playground end-to-end tests

on:
  push:
  pull_request:

permissions: {}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c

    - uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435
      with:
        python-version: "3.11"
        cache: 'pip'

    - name: Install system dependencies
      run: |
        sudo apt-get install libfaketime softhsm2
        echo "PYKCS11LIB=/usr/lib/softhsm/libsofthsm2.so" >> $GITHUB_ENV

    - name: Install Python dependencies
      run: |
        # TODO install repo and signer in separate environments
        python -m pip install pynacl
        python -m pip install pynacl ./playground/repo/
        python -m pip install pynacl ./playground/signer/

    - name: Run tests
      run: |
        cd playground/tests
        ./e2e.sh

    - name: Run Playground unit tests
      run: |
        cd playground/repo
        python -m unittest

    - name: Run tests with DEBUG_TESTS
      if: failure()
      run: |
        cd playground/tests
        DEBUG_TESTS=1 ./e2e.sh
